# Generated by Django 3.1 on 2020-10-19 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0002_auto_20201019_1223'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='slug',
            field=models.SlugField(default=1, max_length=140, unique=True),
            preserve_default=False,
        ),
    ]
